export 'package:widgets_flutter_app/presentation/screens/animated/animated_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/app_tutorial/app_turorial_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/buttons/buttons_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/cards/cards_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/home/home_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/infinite_scroll/infinite_scroll_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/progress_screen/progress_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/snackbar/snackbar_screen.dart';
export 'package:widgets_flutter_app/presentation/screens/ui_controls/ui_controls_screen.dart';
